CONFIG_UBSAN=y
CONFIG_ASAN=y
CONFIG_ETH_NATIVE_TAP=y
CONFIG_NET_CONFIG_AUTO_INIT=y

# Filesystem core
CONFIG_FILE_SYSTEM_LITTLEFS=y
CONFIG_FILE_SYSTEM_MKFS=y

# Flash map & partition support
CONFIG_FLASH=y
CONFIG_FLASH_MAP=y
CONFIG_FLASH_PAGE_LAYOUT=y

# Optional logging
CONFIG_LOG=y

