###############################################################################
# ZEPHYR CONFIGURATION
###############################################################################
# Generic drivers, libraries and frameworks
CONFIG_SMF=y
CONFIG_GPIO=y
CONFIG_HWINFO=y

# Logging
CONFIG_LOG=y
CONFIG_CBPRINTF_FP_SUPPORT=y
CONFIG_LOG_PROCESS_THREAD_SLEEP_MS=200
CONFIG_LOG_BUFFER_SIZE=4512

# Shell
CONFIG_SHELL=y
CONFIG_NET_SHELL=y

# Stacks
CONFIG_MAIN_STACK_SIZE=4512
CONFIG_ISR_STACK_SIZE=4512
CONFIG_SHELL_STACK_SIZE=4500
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=2048

# Heaps
CONFIG_HEAP_MEM_POOL_SIZE=16000

# Real Time Clock (RTC)
CONFIG_RTC=y

# Library
CONFIG_NEWLIB_LIBC=y

# Assertion
CONFIG_ASSERT=y
CONFIG_ASSERT_LEVEL=2

# General networking
CONFIG_NETWORKING=y

# Networking
CONFIG_NET_CONFIG_SETTINGS=y
CONFIG_NET_CONFIG_NEED_IPV4=y

# Data link layer
CONFIG_NET_L2_ETHERNET=y

# Network layer
CONFIG_NET_IPV4=y
CONFIG_NET_CONTEXT_RECV_PKTINFO=y

# Transport layer
CONFIG_NET_SOCKETS=y
CONFIG_NET_UDP=y
CONFIG_NET_TCP=y
CONFIG_NET_TCP_KEEPALIVE=y

# Application layer
CONFIG_NET_HOSTNAME_ENABLE=y
CONFIG_NET_HOSTNAME="firmups-device"

###############################################################################
# MODULE CONFIGURATION
###############################################################################
# LED Button
# CONFIG_C_LED_BUTTON=y
# CONFIG_C_LED_BUTTON_LOG_LEVEL_DBG=y

# Disk access and filesystem
CONFIG_DISK_ACCESS=y
CONFIG_DISK_DRIVERS=y
CONFIG_FILE_SYSTEM=y

# Optional for file system shell
CONFIG_FILE_SYSTEM_SHELL=y

# Can be tinkered with to adjust network speed
CONFIG_NET_PKT_TX_COUNT=14
CONFIG_NET_BUF_TX_COUNT=50
CONFIG_REBOOT=y

CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=8192