manifest:
  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos
    - name: firmups
      url-base: https://github.com/firmups
    - name: firmups-ssh
      url-base: git@github.com:firmups
    - name: mcuboot
      url-base: https://github.com/mcu-tools
  projects:
    - name: zephyr
      path: zephyr
      remote: zephyrproject-rtos
      revision: v4.4.0
      west-commands: scripts/west-commands.yml
      import:
        name-allowlist:
          - cmsis
          - cmsis_6
          - hal_nxp
          - hal_stm32
          - hal_nordic
          - segger
          - fatfs
          - littlefs
          - mcuboot
          - mbedtls
          - tf-psa-crypto
    - name: firmups-device-sdk
      repo-path: device-sdk
      path: ./modules/lib/firmups-device-sdk
      remote: firmups
      revision: gateway-functionality
      submodules: true
    - name: zephyr-bluethoot-integration
      path: ./modules/lib/zephyr-bluethoot-integration
      remote: firmups-ssh
      revision: main
